### ISSUE TITLE
Revisions to data.noaa.gov landing page

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/data.noaa.gov-landing#1]
- [x] Footer is floating, anchor to bottom of page.
- [x] ~508 navigation from ChromeVox jumps from section headers to footer instead of going to the section header description when tabbing through.~ (This isn't how tabbing works; #wontfix)
- [x] ~Use standard OneStop header~ (Waiting for feedback on what header to use)
- [x] The link to NOAA at the bottom goes to HTTPS and that site does not support HTTPS; should be HTTP. (FOIA, Info Quality, external links Disclaimer, and NOAA site updated -- need to do this on OneStop footer as well)
- [x] Text update -> “We are currently providing two approaches to enable searching NOAA's vast data holdings: the traditional NOAA Data Catalog for all data, and the new NOAA OneStop catalog which initially includes only the archived datasets but will eventually replace the traditional catalog”
- [x] Text update ->  “...for selected datasets archived at…” to “... for only those datasets archived at…”
- [x] Use relative links instead of 
  https://data.noaa.gov/onestop use /onestop 
  https://data.noaa.gov/dataset use /dataset
- [x] Rename datasetsearch.html -> index.html

**Comment by ajakz** [comment]
FYI I linked commits with each change to this ticket (sorry to future reviewer that I didn't make a pull request!)

**Comment by mcquinne** [comment]
👍
